name: Caleb Woods
description: Personal site of Caleb Woods
url: http://www.calebwoods.com
permalink: pretty
markdown: redcarpet
highlighter: pygments
exclude: ["Gemfile", "Gemfile.lock", "Rakefile", "examples"]
lsi: true
sass:
  sass_dir: _sass
tag_page_layout: tag_page
tag_page_dir: tags
algolia:
  application_id: 6AST1QVUR2
  index_name: calebwoods.com-posts
gems:
  - algoliasearch-jekyll
